### ISSUE TITLE
Dedicated Maker Taker structure

### ISSUE THREAD

**Issue by mojoX911** [bitcoin-teleport/teleport-transactions#24]
Currently all the maker and taker functionalities are done via open function calls. 
Which works ok, when running demons, but we might wanna eventually have dedicated structure 
for both maker and taker.

This will allow us to get some compile time checking and also have the code organized more structurally.

Opening this issue to open discussion regarding this.

**Comment by chris-belcher** [comment]
Could you write some brief pseudocode to show what you mean?

If I understand right, this would also make it a bit easier to do integration tests in various situations (for example, a taker talking to makers which sometimes stall or misbehave with some random probability)

**Comment by mojoX911** [comment]
Yes I think it will help in those situations to have more fine grained control over maker behavior.

So far what I have in mind is simple refactoring of existing code to introduce a basic structure, 
so instead of calling raw functions like `maker_protocol::start_maker()` we will have something like 
```
let maker = Maker::init(&config);

maker.start();

maker.do_stuffs();

...
```
Same as for Taker.

I can sketch some basic look, and maybe from there we can see what else we might need.

**Comment by mojoX911** [comment]
Heres a code snippet of how it will look like.

https://github.com/mojoX911/teleport-transactions/blob/6c2f4ffcbf2741432c9a5d960dde022a3349f097/src/maker_protocol.rs#L691-L730

And heres how it will be used. 

https://github.com/mojoX911/teleport-transactions/blob/6c2f4ffcbf2741432c9a5d960dde022a3349f097/src/maker_protocol.rs#L979-L992

Let me know if its useful. Its straight forward to do this for both maker and taker, but will take some work, and will include refactoring in `main` module also. So I don't wanna spend too much time on it if it isn't useful.

It might not look much initially but I think it will have certain benefits.

- The code will be better structured and will be easier to reason about.

- We can extend maker structure in future easily however we like to expose various internals. Like a Maker can have a dictionary of connected taker and associated connection-states, etc. In general its much easier to handle structures than bare functions for future extensions.

- In future if we decide to have better wallet or rpc backends, it will be much easier to make the switch in the structure than in bare function calls.

**Comment by chris-belcher** [comment]
Thanks for the explanation. I think it's not that useful. If we end up doing those things in the future then we should do this refactoring then and not before.
